# .github/workflows/deploy.yml
name: Deploy openDAW studio

on:
  workflow_dispatch:
    inputs:
      dry:
        description: "Dry run (check secrets, no upload)"
        required: false
        default: 'true'
        type: boolean

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1. Checkout the main repo with GITHUB_TOKEN (default)
      - name: ⬇️ Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # full history for git log

      # 2. Checkout the private submodule using your PAT
      - name: ⬇️ Checkout private submodule
        uses: actions/checkout@v4
        with:
          repository: andremichelle/opendaw-lib
          path: lib
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
          persist-credentials: false

      # 3. Toolchain & deps
      - name: 🦄 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      # 4. Build (now lib/rebuild.sh exists)
      - name: 🏗️ Build project
        shell: bash
        run: |
          bash ./rebuild.sh


      # 5. Deploy (or dry-run)
      - name: 🚚 Run deploy script
        env:
          TERM: xterm-256color
          SFTP_HOST: ${{ vars.SFTP_HOST }}
          SFTP_PORT: ${{ vars.SFTP_PORT }}
          SFTP_USERNAME: ${{ vars.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DRY_RUN: ${{ inputs.dry && '1' || '0' }}
        run: |
          npx ts-node --transpile-only deploy/run.ts ${{ inputs.dry && '--dry' || '' }}
